"""List of German Area Codes and short forms"""

obj = {
	'augsburg':'a',
	'aalen':'aa',
	'aschaffenburg':'ab',
	'altenburg':'abg',
	'anhalt bitterfeld':'abi',
	'aachen':'ac',
	'auerbach':'ae',
	'ahaus':'ah',
	'aibling':'aib',
	'aichach':'aic',
	'altenkirchen':'ak',
	'alfeld':'alf',
	'alzenau':'alz',
	'amberg':'am',
	'ansbach':'an',
	'annaberg':'ana',
	'angermünde':'ang',
	'anklam':'ank',
	'altötting':'aö',
	'apolda':'ap',
	'arnstadt':'arn',
	'artern':'art',
	'amberg sulzbach':'as',
	'aschersleben':'asl',
	'aue schwarzenberg':'asz',
	'altentreptow':'at',
	'aue':'au',
	'aurich':'aur',
	'ahrweiler':'aw',
	'alzey':'az',
	'anhalt zerbst':'aze',
	'berlin':'b',
	'bamberg':'ba',
	'baden baden':'bad',
	'barnim':'bar',
	'böblingen':'bb',
	'bernburg':'bbg',
	'brandenburgische landesregierung':'bbl',
	'biberach':'bc',
	'buchen':'bch',
	'bundesdienst':'bd',
	'beckum':'be',
	'brand erbisdorf':'bed',
	'bernau':'ber',
	'burgsteinfurt':'bf',
	'berchtesgaden':'bgd',
	'berchtesgadenerland':'bgl',
	'bühl':'bh',
	'bielefeld':'bi',
	'biedenkopf':'bid',
	'bingen':'bin',
	'birkenfeld':'bir',
	'bitburg':'bit',
	'bischofswerda':'biw',
	'backnang':'bk',
	'bernkastel':'bks',
	'balingen':'bl',
	'berleburg':'blb',
	'burgenlandkreis':'blk',
	'bergheim':'bm',
	'bonn':'bn',
	'borna':'bna',
	'bochum':'bo',
	'börde':'bö',
	'bogen':'bog',
	'bocholt':'boh',
	'borken':'bor',
	'bottrop':'bot',
	'bundespolizei':'bp',
	'bundes polizei':'bp',
	'polizei':'bp',
	'brake':'bra',
	'brandenburg':'brb',
	'burg':'brg',
	'brückenau':'brk',
	'braunlage':'brl',
	'bremervörde':'brv',
	'braunschweig':'bs',
	'bersenbrück':'bsb',
	'beeskow':'bsk',
	'bayreuth':'bt',
	'bitterfeld':'btf',
	'büdingen':'büd',
	'burglengenfeld':'bul',
	'büren':'bür',
	'büsingen':'büs',
	'bützow':'büz',
	'bundes wasserstraßen und schifffahrtsverwaltung':'bw',
	'bundes wasserstraßen schifffahrtsverwaltung':'bw',
	'baden württembergischer landtag':'bwl',
	'bayerischer landtag':'byl',
	'bautzen':'bz',
	'chemnitz':'c',
	'calau':'ca',
	'castrop':'cas',
	'cottbus':'cb',
	'celle':'ce',
	'zelle':'ce',
	'cham':'cha',
	'cloppenburg':'clp',
	'clausthal zellerfeld':'clz',
	'coburg':'co',
	'cochem':'coc',
	'coesfeld':'coe',
	'crailsheim':'cr',
	'cuxhaven':'cux',
	'calw':'cw',
	'düsseldorf':'d',
	'darmstadt':'da',
	'dachau':'dah',
	'dannenberg':'dan',
	'daun':'dau',
	'doberan':'dbr',
	'dresden':'dd',
	'dessau':'de',
	'deggendorf':'deg',
	'delmenhorst':'del',
	'dingolfing':'dgf',
	'diepholz':'dh',
	'dieburg':'di',
	'dillenburg':'dil',
	'dinslaken':'din',
	'diez':'diz',
	'dinkelsbühl':'dkb',
	'döbeln':'dl',
	'dillingen':'dlg',
	'demmin':'dm',
	'düren':'dn',
	'dortmund':'do',
	'donauwörth':'don',
	'duisburg':'du',
	'duderstadt':'dud',
	'dürkheim an der weinstraße':'düw',
	'dippoldiswalde':'dw',
	'delitzsch':'dz',
	'essen':'e',
	'eisenach':'ea',
	'eilenburg':'eb',
	'ebersberg':'ebe',
	'ebern':'ebn',
	'ebermannstadt':'ebs',
	'eckernförde':'eck',
	'erding':'ed',
	'elbe elster':'ee',
	'erfurt':'ef',
	'eggenfelden':'eg',
	'eisenhüttenstadt':'eh',
	'eichstätt':'ei',
	'eichsfeld':'eic',
	'eisleben':'eil',
	'einbeck':'ein',
	'eisenberg':'eis',
	'emsland':'el',
	'emmendingen':'em',
	'emden':'emd',
	'ems':'ems',
	'ennepe':'en',
	'erlangen':'er',
	'erbach':'erb',
	'erlangen höchstadt':'erh',
	'erkelenz':'erk',
	'erzgebirge':'erz',
	'esslingen':'es',
	'eschenbach':'esb',
	'eschwege':'esw',
	'euskirchen':'eu',
	'eberswalde':'ew',
	'frankfurt':'f',
	'frankfurt am main':'f',
	'frankfurt main':'f',
	'wetteraukreis':'fb',
	'fulda':'fd',
	'friedberg':'fdb',
	'freudenstadt':'fds',
	'feuchtwangen':'feu',
	'frankfurt oder':'ff',
	'fürstenfeldbruck':'ffb',
	'freiberg':'fg',
	'finsterwalde':'fi',
	'frankenberg':'fkb',
	'flensburg':'fl',
	'flöha':'flö',
	'friedrichshafen':'fn',
	'forchheim':'fo',
	'forst':'for',
	'freiburg':'fr',
	'freyung grafenau':'frg',
	'friesland':'fri',
	'freienwalde':'frw',
	'freising':'fs',
	'frankenthal':'ft',
	'freital':'ftl',
	'fürth':'fü',
	'füssen':'füs',
	'fürstenwalde':'fw',
	'fritzlar':'fz',
	'gera':'g',
	'gardelegen':'ga',
	'gandersheim':'gan',
	'garmisch partenkirchen':'gap',
	'glauchau':'gc',
	'gmünd':'gd',
	'gadebusch':'gdb',
	'gelsenkirchen':'ge',
	'geldern':'gel',
	'gerolzhofen':'geo',
	'germersheim':'ger',
	'gifhorn':'gf',
	'groß gerau':'gg',
	'geithain':'gha',
	'gräfenhainichen':'ghc',
	'gießen':'gi',
	'geilenkirchen':'gk',
	'gladbach':'gl',
	'gladbeck':'gla',
	'gummersbach':'gm',
	'grimmen':'gmn',
	'gelnhausen':'gn',
	'genthin':'gnt',
	'göttingen':'gö',
	'goar':'goa',
	'goarshausen':'goh',
	'göppingen':'gp',
	'görlitz':'gr',
	'grafenau':'gra',
	'großenhain':'grh',
	'griesbach':'gri',
	'grimma':'grm',
	'greiz':'grz',
	'goslar':'gs',
	'gütersloh':'gt',
	'gotha':'gth',
	'güstrow':'gü',
	'guben':'gub',
	'gunzenhausen':'gun',
	'grevenbroich':'gv',
	'grevesmühlen':'gvm',
	'greifswald':'gw',
	'günzburg':'gz',
	'hannover':'h',
	'hanover':'h',
	'hagen':'ha',
	'hammelburg':'hab',
	'halle':'hal',
	'hamm':'ham',
	'hassfurt':'has',
	'bremen':'hb',
	'hansestadt bremen':'hb',
	'hildburghausen':'hbn',
	'halberstadt':'hbs',
	'hainichen':'hc',
	'hechingen':'hch',
	'heidelberg':'hd',
	'heidenheim':'hdh',
	'haldensleben':'hdl',
	'helmstedt':'he',
	'hersbruck':'heb',
	'hersfeld':'hef',
	'heide':'hei',
	'hessischer landtag':'hel',
	'herne':'her',
	'hettstedt':'het',
	'herford':'hf',
	'bad homburg':'hg',
	'hagenow':'hgn',
	'hansestadt greifswald':'hgw',
	'hamburg':'hh',
	'hansestadt hamburg':'hh',
	'freie und hansestadt hamburg':'hh',
	'freie hansestadt hamburg':'hh',
	'hohenmölsen':'hhm',
	'hildesheim':'hi',
	'heiligenstadt':'hig',
	'hilpoltstein':'hip',
	'heidekreis':'hk',
	'lübeck':'hl',
	'hansestadt lübeck':'hl',
	'hameln':'hm',
	'hann münden':'hmü',
	'hannoversch münden':'hmü', 
	'heilbronn':'hn',
	'hof':'ho',
	'hofgeismar':'hog',
	'hofheim':'hoh',
	'holzminden':'hol',
	'homburg':'hom',
	'horb':'hor',
	'höchstadt':'hös',
	'hohenstein':'hot',
	'heppenheim':'hp',
	'homberg':'hr',
	'landkreis rostock':'lro',
	'hansestadt rostock':'hro',
	'rostock':'ros',
	'heinsberg':'hs',
	'hochsauerlandkreis':'hsk',
	'stralsund':'hst',
	'hansestadt stralsund':'hst',
	'hanau':'hu',
	'havelberg':'hv',
	'havelland':'hvl',
	'höxter':'hx',
	'hoyerswerda':'hy',
	'harz':'hz',
	'ingbert':'igb',
	'ilm kreis':'ik',
	'ilmenau':'il',
	'illertissen':'ill',
	'ingolstadt':'in',
	'itzehoe':'iz',
	'jena':'j',
	'jessen':'je',
	'jerichower land':'jl',
	'jülich':'jül',
	'köln':'k',
	'karlsruhe':'ka',
	'korbach':'kb',
	'kronach':'kc',
	'kempten':'ke',
	'kelheim':'keh',
	'kehl':'kel',
	'kemnath':'kem',
	'kaufbeuren':'kf',
	'kissingen':'kg',
	'kreuznach':'kh',
	'kiel':'ki',
	'kirchheimbolanden':'kib',
	'kempen, krefeld':'kk',
	'kaiserslautern':'kl',
	'kleve':'kle',
	'klötze':'klz',
	'kamenz':'km',
	'konstanz':'kn',
	'koblenz':'ko',
	'königshofen':'kön',
	'köthen':'köt',
	'kötzting':'köz',
	'krefeld':'kr',
	'krumbach':'kru',
	'kassel':'ks',
	'kitzingen':'kt',
	'kulmbach':'ku',
	'künzelsau':'kün',
	'kusel':'kus',
	'königs wusterhausen':'kw',
	'kyritz':'ky',
	'kyffhäuser':'kyf',
	'leipzig':'l',
	'landshut':'la',
	'landau':'lan',
	'lauf':'lau',
	'ludwigsburg':'lb',
	'lobenstein':'lbs',
	'lübz':'lbz',
	'luckau':'lc',
	'dingolfing landau':'ld',
	'lahn dill kreis':'ldk',
	'landkreis dahme spreewald':'lds',
	'leonberg':'leo',
	'leer':'ler',
	'leverkusen':'lev',
	'laufen':'lf',
	'lüneburg':'lg',
	'lüdinghausen':'lh',
	'lindau':'li',
	'liebenwerda':'lib',
	'lichtenfels':'lif',
	'lippe':'lip',
	'landsberg am lech':'ll',
	'limburg':'lm',
	'lübben':'ln',
	'lörrach':'lö',
	'löbau':'löb',
	'landkreis oder spre':'los',
	'lippstadt':'lp',
	'lahr':'lr',
	'land sachsen anhalt':'lsa',
	'landtag sachsen':'lsn',
	'langensalza':'lsz',
	'ludwigshafen':'lu',
	'lünen':'lün',
	'ludwigslust, parchim':'lup',
	'ludwigslust':'lwl',
	'münchen':'m',
	'mannheim':'ma',
	'marienberg':'mab',
	'mainburg':'mai',
	'marktredwitz':'mak',
	'mallersdorf':'mal',
	'miesbach':'mb',
	'malchin':'mc',
	'magdeburg':'md',
	'mettmann':'me',
	'meldorf':'med',
	'melsungen':'meg',
	'meißen':'mei',
	'mittlerer erzgebirgskreis':'mek',
	'melle':'mel',
	'merseburg':'mer',
	'mellrichstadt':'met',
	'mönchengladbach':'mg',
	'mergentheim':'mgh',
	'meiningen':'mgn',
	'mülheim':'mh',
	'mühlhausen':'mhl',
	'minden':'mi',
	'miltenberg':'mil',
	'märkischer kreis':'mk',
	'main kinzig kreis':'mkk',
	'mansfelder land':'ml',
	'memmingen':'mm',
	'mindelheim':'mn',
	'moers':'mo',
	'marktoberdorf':'mod',
	'märkisch oderland':'mol',
	'monschau':'mon',
	'mosbach':'mos',
	'merseburg querfurt':'mq',
	'marburg':'mr',
	'münster':'ms',
	'mecklenburgische seenplatte':'mse',
	'mansfeld südharz':'msh',
	'main spessart':'msp',
	'mecklenburg strelitz':'mst',
	'main taunus kreis':'mtk',
	'muldental':'mtl',
	'mühldorf':'mü',
	'münchberg':'müb',
	'müritz':'mür',
	'mecklenburg vorpommerscher landtag':'mvl',
	'mittweida':'mw',
	'mayen':'my',
	'mayen koblenz':'myk',
	'mainz':'mz',
	'merzig':'mzg',
	'nürnberg':'n',
	'nabburg':'nab',
	'naila':'nai',
	'nauen':'nau',
	'neubrandenburg':'nb',
	'neuburg an der donau':'nd',
	'nordhausen':'ndh',
	'neuss':'ne',
	'neustadt an der aisch':'nea',
	'nebra':'neb',
	'neustadt bei coburg':'nec',
	'neunburg':'nen',
	'neustadt an der saale':'nes',
	'neustadt an der waldnaab':'new',
	'nordfriesland':'nf',
	'neuhaus':'nh',
	'nienburg':'ni',
	'neunkirchen':'nk',
	'niedersächsischer landtag':'nl',
	'neumarkt':'nm',
	'naumburg':'nmb',
	'neumünster':'nms',
	'nördlingen':'nö',
	'nordhorn':'noh',
	'niederschlesische oberlausitz':'nol',
	'northeim':'nom',
	'norden':'nor',
	'neuruppin':'np',
	'neuwied am rhein':'nr',
	'nordrhein westfalen':'nrw',
	'nürtingen':'nt',
	'neu ulm':'nu',
	'nordvorpommern':'nvp',
	'neustadt an der weinstraße':'nw',
	'nordwestmecklenburg':'nwm',
	'niesky':'ny',
	'neustrelitz':'nz',
	'oberallgäu':'oa',
	'ostallgäu':'oal',
	'oberhausen':'ob',
	'obernburg':'obb',
	'osterburg':'obg',
	'oschersleben':'oc',
	'ochsenfurt':'och',
	'oldesloe':'od',
	'olpe':'oe',
	'offenbach':'of',
	'offenburg':'og',
	'ostholstein':'oh',
	'osterode am harz':'oha',
	'öhringen':'öhr',
	'oberhavel':'ohv',
	'osterholz':'ohz',
	'ohrekreis':'ok',
	'oldenburg':'ol',
	'opladen':'op',
	'ostprignitz, ruppin':'opr',
	'osnabrück':'os',
	'oberspreewald lausitz':'osl',
	'oberviechtach':'ovi',
	'obervogtland':'ovl',
	'oschatz':'oz',
	'potsdam':'p',
	'passau':'pa',
	'pfaffenhofen':'paf',
	'pfarrkirchen':'pan',
	'parsberg':'par',
	'paderborn':'pb',
	'parchim':'pch',
	'peine':'pe',
	'pegnitz':'peg',
	'pforzheim':'pf',
	'pinneberg':'pi',
	'pirna':'pir',
	'plauen':'pl',
	'plön':'plö',
	'potsdam mittelmark':'pm',
	'pößneck':'pn',
	'prignitz':'pr',
	'prüm':'prü',
	'pirmasens':'ps',
	'pasewalk':'pw',
	'prenzlau':'pz',
	'querfurt':'qft',
	'quedlinburg':'qlb',
	'regensburg':'r',
	'württemberg':'ra',
	'reichenbach':'rc',
	'rendsburg':'rd',
	'ribnitz damgarten':'rdg',
	'recklinghausen':'re',
	'regen':'reg',
	'rehau':'reh',
	'reichenhall':'rei',
	'rems murr kreis':'wn',
	'rems murr':'wn',
	'riesa großenhain':'rg',
	'roth':'rh',
	'rinteln':'ri',
	'riedenburg':'rid',
	'riesa':'rie',
	'rochlitz':'rl',
	'röbel müritz':'rm',
	'rathenow':'rn',
	'rosenheim':'ro',
	'roding':'rod',
	'rotenburg an der fulda':'rof',
	'rockenhausen':'rok',
	'rottenburg an der laaber':'rol',
	'rothenburg ob der tauber':'rot',
	'rothenburg':'rot',
	'rotenburg wümme':'row',
	'rhein pfalz':'rp',
	'rheinland pfälzischer landtag':'rpl',
	'remscheid':'rs',
	'rosslau':'rsl',
	'reutlingen':'rt',
	'rudolstadt':'ru',
	'rüdesheim':'rüd',
	'rügen':'rüg',
	'ravensburg':'rv',
	'rottweil':'rw',
	'ratzeburg':'rz',
	'stuttgart':'s',
	'saarburg':'sab',
	'schwandorf':'sad',
	'saarländischer landtag':'sal',
	'stadtsteinach':'san',
	'salzwedel':'saw',
	'saarbrücken':'sb',
	'strasburg':'sbg',
	'schönebeck':'sbk',
	'schwabach':'sc',
	'schleiz':'scz',
	'sondershausen':'sdh',
	'stendal':'sdl',
	'schwedt':'sdt',
	'segeberg':'se',
	'sebnitz':'seb',
	'seelow':'see',
	'scheinfeld':'sef',
	'selb':'sel',
	'senftenberg':'sfb',
	'staßfurt':'sft',
	'solingen':'sg',
	'sangerhausen':'sgh',
	'schleswig holstein':'sh',
	'schwäbisch hall':'sha',
	'stadthagen':'shg',
	'saale holzland kreis':'shk',
	'suhl':'shl',
	'siegen':'si',
	'sigmaringen':'sig',
	'simmern':'sim',
	'saalekreis':'sk',
	'schleswig':'sl',
	'schleiden':'sle',
	'saalfeld':'slf',
	'salzlandkreis':'slk',
	'schmölln':'sln',
	'saarlouis':'sls',
	'schlüchtern':'slü',
	'salzungen':'slz',
	'schmalkalden':'sm',
	'schwabmünchen':'smü',
	'schwerin':'sn',
	'soest':'so',
	'schrobenhausen':'sob',
	'schongau':'sog',
	'saale orla kreis':'sok',
	'sömmerda':'söm',
	'sonneberg':'son',
	'speyer':'sp',
	'spremberg':'spb',
	'spree neiße':'spn',
	'straubing':'sr',
	'strausberg':'srb',
	'stadtroda':'sro',
	'steinfurt':'st',
	'starnberg':'sta',
	'sternberg':'stb',
	'stade':'std',
	'staffelstein':'ste',
	'stollberg':'stl',
	'siegburg':'su',
	'sulzbach':'sul',
	'südliche weinstraße':'süw',
	'schweinfurt':'sw',
	'schwalbach':'swa',
	'syke':'sy',
	'salzgitter':'sz',
	'schwarzenberg':'szb',
	'tauberbischofsheim':'tbb',
	'torgau delitzsch oschatz':'tdo',
	'tecklenburg':'te',
	'teterow':'tet',
	'teltow fläming':'tf',
	'torgau':'tg',
	'thüringer landtag':'thl',
	'technisches hilfswerk':'thw',
	'tirschenreuth':'tir',
	'torgau oschatz':'to',
	'tölz':'töl',
	'templin':'tp',
	'trier':'tr',
	'traunstein':'ts',
	'tübingen':'tü',
	'tuttlingen':'tut',
	'uelzen':'ue',
	'ueckermünde':'uem',
	'uffenheim':'uff',
	'unstrut hainich':'uh',
	'ulm':'ul',
	'uckermark':'um',
	'unna':'un',
	'usingen':'usi',
	'vogtland':'v',
	'vaihingen':'vai',
	'vogelsberg':'vb',
	'vechta':'vec',
	'verden':'ver',
	'vorpommern greifswald':'vg',
	'vilsbiburg':'vib',
	'viersen':'vie',
	'viechtach':'vit',
	'völklingen':'vk',
	'vohenstrauß':'voh',
	'vorpommern rügen':'vr',
	'villingen schwenningen':'vs',
	'wuppertal':'w',
	'waldeck':'wa',
	'warendorf':'waf',
	'wartburgkreis':'wak',
	'wanne':'wan',
	'wattenscheid':'wat',
	'wittenberg':'wb',
	'worbis':'wbs',
	'werdau':'wda',
	'weimar':'we',
	'weilburg':'wel',
	'weiden':'wen',
	'wertingen':'wer',
	'wesel':'wes',
	'wolfenbüttel':'wf',
	'wilhelmshaven':'whv',
	'wiesbaden':'wi',
	'wittlich':'wil',
	'wismar':'wis',
	'hansestadt wismar':'hwi',
	'witten':'wit',
	'witzenhausen':'wiz',
	'wittstock':'wk',
	'winsen luhe':'wl',
	'wolgast':'wlg',
	'weilheim':'wm',
	'wolmirstedt':'wms',
	'waiblingen':'wn',
	'wendel':'wnd',
	'worms':'wo',
	'wolfsburg':'wob',
	'wolfhagen':'woh',
	'wolfach':'wol',
	'wolfratshausen':'wor',
	'wolfstein':'wos',
	'wernigerode':'wr',
	'waren':'wrn',
	'wasserburg':'ws',
	'weissenfels':'wsf',
	'westerstede':'wst',
	'weisswasser':'wsw',
	'waldshut':'wt',
	'wittlage':'wtl',
	'wittmund':'wtm',
	'würzburg':'wü',
	'weißenburg':'wug',
	'waldmünchen':'wüm',
	'wunsiedel':'wun',
	'wurzen':'wur',
	'westerwald':'ww',
	'wetzlar':'wz',
	'wanzleben':'wzl',
	'bundeswehr':'y',
	'zwickau':'z',
	'zerbst':'ze',
	'zell':'zel',
	'zittau':'zi',
	'ziegenhain':'zig',
	'zschopau':'zp',
	'zeulenroda':'zr',
	'zweibrücken':'zw',
	'zeitz':'zz'
}